PROGRAM GAUSS_ELIMINATION

!THE FOLLOWING CODE HAS BEEN DEVELOPED TO SOLVE A SYSTEM OF N EQUATIONS
!WITH N VARIABLES WHICH TAKE UP THE FORM OF [A][X] = [C] IN MATRICES WHERE
![A] = COEFFICIENT MATRIX
![X] = UNKNOWN VECTOR
![C] = SOLITION VECTOR


REAL, DIMENSION(20, 20):: A

REAL, DIMENSION(20):: X, C

REAL F, SUM

INTEGER I, J, K, N

PRINT*, "ENTER THE NUMBER OF EQUATIONS YOU WANT TO SOLVE"
READ*, N


PRINT*, "ENTER THE ELEMENTS IN COEFFICIENT MATRIX"

DO I = 1, N
  DO J = 1, N
    READ*, A(I, J)
  END DO
END DO

PRINT*, "ENTER THE ELEMENTS IN SOLUTION VECTOR"

DO I = 1, N
  READ*, C(I)
END DO

!FORWARD ELIMINATION

DO K = 1, N-1
  DO I = K+1, N

    F = A(I,K)/A(K,K)

    DO J = 1, N
      A(I,J) = A(I,J) - F*A(K,J)
    END DO

    C(I) = C(I) - F*C(K)

  END DO
END DO

PRINT*, "THE COEFFICIENT MATRIX AFTER FORWARD ELIMINATION IS"

DO I = 1, N
  DO J= 1, N
    PRINT*, A(I,J)
  END DO
  PRINT*, " "
END DO

PRINT*, " "  

PRINT*, "THE SOLUTION VECTOR AFTER FORWARD ELIMINATION IS"  
  
DO I = 1, N
  PRINT*, C(I)
END DO

  
!BACK SUBSTITUTION

X(N) = C(N)/A(N,N)

DO I = N-1, 1, -1
 SUM = 0
 DO J = I+1, N
   SUM = SUM + A(I,J)*X(J)
 END DO
 X(I) = (C(I)-SUM)/A(I,I)
END DO

 
PRINT*, "THE SOLUTION OF THE EQUATION IS"

DO I= 1, N
  PRINT*, X(I)
END DO

  

END PROGRAM